### ISSUE TITLE
Duplication and wrong search index

### ISSUE THREAD

**Issue by rosenbergd** [aeyonblack/oc-assessment#1]
https://github.com/aeyonblack/oc-assessment/blob/1c56b2fde35ebf5666e1e4ed4b2afce95d270200/app/src/main/java/com/example/feldmantest/ui/MainActivity.kt#L113-L125

There's duplication of code here for the for inside the for (posts and comments nested for loops) as well as an error in the code that replaces it where it uses comment's ID instead of post ID

**Comment by aeyonblack** [comment]
Issue has been fixed
